micronaut:
  application:
    name: source-oracle-v2

airbyte:
  connector:
    configurationClass: "io.airbyte.integrations.source.oracle.ConfigurationPOJO"
    documentationUrl: "https://docs.airbyte.com/integrations/sources/oracle"